ocf/ocfweb

ocfweb/docs/docs/staff/backend/jessie.md

Attempts to fix [this page](https://dev.ocf.berkeley.edu/docs/staff/backend/jessie/) (image below) into a table by using markdown formatting instead of straight HTML.

Fix table on jessie migration staff docs

---

ocfweb/component/markdown.py
ocfweb/docs/templatetags/docs.py

Strip HTML when printing ToC and generating IDs

---

ocfweb/main/templates/home.html
ocfweb/static/scss/pages/home.scss

We were double padding since Bootstrap pads list items by default.
https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_type.scss#L179
```css
// Inline turns list items into inline-block
.list-inline {
@include list-unstyled;
margin-left: -5px;
> li {
display: inline-block;
padding-left: 5px;
padding-right: 5px;
}
}
```

Fix staff hours head spacing

---

ocfweb/static/scss/pages/docs.scss

Even on the useless h5 and h6.

Fix heading anchor link icon size

---

ocfweb/static/scss/site.scss

Hovering only opens the dropdown, while clicking activates the link and holds the dropdown open while it has focus. The behavior seems consistent enough to be usable.

Open services dropdown on hover

---

ocfweb/static/scss/site.scss

Follow-up to @matthew-mcallister's #62 
This gives us the same "open" styling as when clicking if you hover:

Use open style on dropdown nav item on hover

---

.scss-lint.yml
ocfweb/docs/docs/contact.md
ocfweb/main/templates/staff-hours.html
ocfweb/static/scss/ocf.scss
ocfweb/static/scss/pages/home.scss
ocfweb/static/scss/site.scss
ocfweb/templates/base.html

This makes the home page (and some other areas of the site) look a lot better on mobile.
There are a bunch of minor fixes (most of which you can't see on the screenshots below).
before:
after:
There's still a big variance in mobile screen sizes (especially iPhone < 6). You can use Chrome's dev tools to simulate them easily.
Once this is merged we can launch!

More responsive home page

---

ocfweb/static/scss/pages/docs.scss

Previously anchors would take you to the header exactly, but the 60px fixed OCF navbar would cover the heading.
before:
after:
This hacks an empty block before it to offset it. It doesn't affect how the page looks at all, but makes the anchors behave properly.

Offset anchors on docs

---

ocfweb/docs/doc.py
ocfweb/docs/templates/doc.html
ocfweb/static/scss/pages/docs.scss

This closes #14 
This makes it a little easier for staff to make quick edits, and also suggests to random visitors that their contributions are welcome (as unlikely as they might be to make them).
If you try to make edits without having write access to the repo, you'll be lead through forking the repo and then submitting a pull request.

Add "Edit this Page" link at bottom of Markdown docs

---

.pre-commit-config.yaml
requirements-dev.txt

This switches us to a pre-commit branch I'm developing that allows hooks to target files by "type" rather than merely extension. This means that it can, for example, target "all text files" or "all Python files, even if they only have a Python shebang but no extension".
The branch seems to be pretty stable but I'd like to get some more real-world testing, hence switching some OCF projects to use it.
The main changes you see here are switching the hooks repos to my own forks that declare hooks by type instead of extension, plus removing some things we no longer have to exclude (my branch fixes issues with submodules and symlinks being treated as regular files by some bad hooks).
OCF has Debian packages for the fork uploaded, and you can pip install it as `ckuehl-pre-commit-types` (you …

Temporarily switch to pre-commit-by-types fork

---

ocfweb/stats/summary.py
ocfweb/stats/templates/summary.html

Use the current time as the ending time for lab utilization stats if the lab has not closed yet to give accurate idle, busy and percentage usage values for a day. Also make sure the percentage isn't negative if the lab hasn't opened yet for a day.
I definitely haven't been here for 461 minutes today, I swear...

Fix lab utilization numbers

---

ocfweb/stats/summary.py
ocfweb/stats/templates/summary.html
ocfweb/templates/partials/progress-bar.html
ocfweb/templatetags/ui_components.py

Unfortunately text on Bootstrap progress bars is unreadable when the bars get too short, so I just left the labels blank. I think it still looks kinda reasonable though...
On small screens (phones) they're in the same column which still looks fine:

stats: add basic printing numbers

---

ocfweb/caching.py

If the key expires between when we check if it's in the cache and when we call `get`, we might return `None` in error.

Fix rare race condition in caching code

---

ocfweb/bin/run_periodic_functions.py
ocfweb/caching.py
ocfweb/component/blog.py
ocfweb/main/home.py
ocfweb/settings.py
ocfweb/test/periodic.py
ocfweb/test/templates/periodic.html
ocfweb/urls.py
setup.py
tests/caching_test.py

Right now on ocfweb we have a lot of really slow calls:
* loading blog posts
* loading staff hours (mostly LDAP)
* loading lab_status (HTTP to death)
* loading stats
Some of these are behind a caching decorator, where the result is saved for some seconds (but one poor user still has to wait a long time to view the page, and because of low traffic on some of the pages, lots of users end up being poor users).
This introduces periodic functions. The docstring explains pretty well:
```python
def periodic(period, ttl=None):
"""Caching function decorator for functions which desire TTL-based caching.
Using this decorator on a function registers it as a "periodic function",
with the given period in seconds. The function will be run in the
background at the requested frequency.
When the function …
```

Add start of periodic functions

---

ocfweb/stats/templates/summary.html

I think this looks a bit better and is a little easier to read.

Put printer stats in a column

---

ocfweb/settings.py

We do this for the session cookie, we should do it for the CSRF token too.
https://docs.djangoproject.com/en/1.9/ref/settings/#std:setting-CSRF_COOKIE_NAME

Rename csrftoken cookie and make it HTTP-only

---

ocfweb/docs/doc.py
ocfweb/docs/markdown_based.py

Addresses #136.
Unfortunately, reloading page _titles_ in development is not as easy, since they are stored in the documents themselves and require reading all of the markdown files every load to generate the proper trees. The current page title will update with these changes, but the same page's title shown on other pages will not change. Not sure if there is a better way to change that other than reading in all of the markdown files, but changing page titles should happen far less than changing their contents. New markdown files are also not recognized, so maybe reading in all the files would work well to fix these additional issues?

Reload docs in development

---

ocfweb/templatetags/lab_hours.py

I think we didn't notice they were missing because we're used to the way they're presented now. It seemed like a good idea to hide the minute when we open/close unless either is not on the hour, i.e. 9:10am-6:00pm on Tuesday but 9am-9pm on regular days.

Show minutes in lab hours when relevant

---

ocfweb/docs/templates/commands.html
ocfweb/docs/urls.py
ocfweb/docs/views/commands.py
ocfweb/static/scss/pages/docs.scss
ocfweb/static/scss/pages/docs/commands.scss

@daradib suggested this several weeks ago. It seems like a modestly helpful improvement over logging directly into ssh.o.b.e from a browser.
I duplicated the OCF command table to include some basic file manipulation help. I don't know if it's worth keeping, but, if we do so, the table could be made into a partial template and the reference section expanded.
Also, I couldn't get the iframe to properly scale while keeping aspect ratio, so this is my attempt at responsive.

docs: create a live command reference page

---

debian/rules

pyparsing 2.1.2 was just released today: https://pypi.python.org/pypi/pyparsing/2.1.2
we pin pyparsing==2.1.1 so there's no reason 2.1.2 should have been installed in our built package, but it was
something broken in pyparsing 2.1.1 gave us weird tracebacks, only in prod (dev was fine, since using 2.1.1): https://gist.github.com/anonymous/9d1cd2db89f20495267c141bc0dbccd7
turns out our use of --upgrade was incorrect in debian/rules:
https://github.com/ocf/ocfweb/blob/7dd738931f1d942d6444fe3c1c18db06a127fb87/debian/rules#L19
the --upgrade meant that when dh-virtualenv did "pip install [ocfweb]" it would actually upgrade dependencies, even if older (pinned) versions were already installed
now that we pin a specific version of pip (due to https://github.com/ocf/ocfweb/pull/160) we can drop …

Fix broken requirements pinning in prod

---

.scss-lint.yml
ocfweb/account/templates/account/vhost_mail/index.html
ocfweb/account/vhost_mail.py
ocfweb/static/scss/pages/account.scss
ocfweb/static/scss/pages/account/vhost_mail.scss
ocfweb/templatetags/common.py

This adds the functionality to the main view and the add modal. There's still no "edit forward to" modal, but this is designed in such a way as it's straightforward to add later.
the edit links on the first 2 columns don't do anything yet

vhost mail: add support for multiple "forward to" addresses

---

ocfweb/account/templates/account/partials/vhost_mail/modals/add-address.html
ocfweb/account/templates/account/vhost_mail/index.html
ocfweb/account/templatetags/vhost_mail.py
ocfweb/account/vhost_mail.py
ocfweb/static/js/pages/account/vhost_mail.js
ocfweb/static/scss/pages/account/vhost_mail.scss
tests/account/vhost_mail_test.py

This is what it looks like if you haven't set a catch-all email:
Here's the modal where you add one (same as the normal add modal, but with the incoming address and password fields omitted):
Here's what it looks like when you have a catch-all email:
(The popovers obviously start closed, I just opened them for the sake of the screenshots.)

Add catch-all support for vhost mail

---

ocfweb/about/templates/about/staff.html
ocfweb/docs/docs/about.md

I think this is the third time I changed the home page to
just say printing like our other free as in beer services.
This time we have version control. Long live version control.

Remove "free" before printing

---

.dockerignore
Dockerfile
Jenkinsfile
Makefile
conf/ocfweb.conf
debian/postinst
ocfweb/settings.py
services/ocfweb/run
services/redis-tunnel/run

This isn't fully done right now. I think this is enough to work in prod
(where we have the secrets we need -- we'll find out), but definitely
not in dev yet.
There are also some other things that would eventually need to do before
we can replace coma with this, at least:
* The background worker doesn't run in this new setup yet
* Static files are still served from static.ocf.b.e which is coma

Add a Dockerfile and some related config

---

Jenkinsfile

There's no point running the `test-cook-image` stage on master, because we're about to do the actual `cook-image` for prod, which would fail anyway.

Only run test-cook-image for branches (not master)

---

ocfweb/settings.py

Django 1.10.3 introduced a [change in the behavior of ALLOWED_HOSTS][1]
that breaks our debug mode. This change allows `make dev` to continue
launching a usable website, by listing the local host as an allowed host
in debug mode.
[1]: https://docs.djangoproject.com/en/1.10/releases/1.10.3/#dns-rebinding-vulnerability-when-debug-true

settings: add local host to ALLOWED_HOSTS in debug mode

---

ocfweb/docs/docs/staff.md

Doing this for the tech talk, looks like we didn't have a link to staff hours from the docs before, strangely enough.
Pretty **cool** stuff yo!

Add link to staff hours from docs

---

ocfweb/docs/docs/services/mail.md

In particular, updating your contact email address via update-email is required
of both student groups and individual accounts.

docs: Update mail forwarding and vhost info

---

Jenkinsfile

Currently if you push to ocflib, it rebuilds every single ocfweb branch, which is probably unnecessary.

Only add a reverse trigger on ocflib if we're master

---

ocfweb/docs/docs/staff/backend/mesos.md

This adds a high-level overview of how Mesos/Marathon/Zookeeper fit together in general (and at the OCF).
The plan is to later add sub-pages for each of these which discuss how to troubleshoot each component, as well as giving links to web UIs and general "how-to" topics.
Marathon would probably need more information about actually writing apps to be deployed by it, and how to deploy them.

Add a first draft of Mesos documentation

---

ocfweb/account/chpass.py
ocfweb/account/register.py
ocfweb/component/lab_status.py
ocfweb/templates/create_disabled.html
ocfweb/templates/group_accounts_only.html

This lets us turn off create based on a config option if create is broken for some reason.
Obviously we want to minimize this time, but it's useful when testing changes to create, since we can make sure users won't get a broken experience.

Add option to disable pages depending on create

---

vendor/venv-update

This fixes a bunch of issues like the concurrent cache miss bug that we sometimes hit on Jenkins.
Most of the changes are not in the vendored file but are in the venv-update package downloaded from PyPI, so this diff isn't very interesting.

Update venv-update to 2.0.0

---

ocfweb/docs/templates/docs/partials/host.html
ocfweb/static/scss/pages/docs/_servers.scss

I found myself often going to /docs/backend/servers/ to recall which VM corresponded to which task, this just adds a nice jump directly to the server name. For example, 
http://nyx.ocf.berkeley.edu:8934/docs/staff/backend/servers/#supernova

add anchors to server rows

---

ocfweb/component/celery.py
requirements-minimal.txt
requirements.txt

~~still using spiped for redis locking~~ that doesn't actually happen in ocfweb anyway

Upgrade to celery 4, use stunnel instead of spiped

---

.pre-commit-config.yaml
Makefile
README.md
ocfweb/docs/docs/staff/staffvm.md
requirements-dev-minimal.txt
requirements-dev.txt
requirements.txt

We don't need it for ocfweb (utils and puppet are the only repos that
need it).

Stop using my pre-commit fork

---

ocfweb/announcements/announcements.py
ocfweb/announcements/templates/announcements/2017-03-01-hpc-survey.html

A bit long I admit, but not as long as the survey. I plan to post this by the evening.
This is also the last chance to make comments on the survey itself, as I'm going to lock it when I post this announcement.
http://supernova.ocf.berkeley.edu:8108/announcements/2017-03-01/hpc-survey

announcements: Post HPC interest survey

---

ocfweb/announcements/announcements.py
ocfweb/announcements/templates/announcements/2017-03-01-hpc-survey.html
ocfweb/announcements/templates/announcements/2017-03-20-hiring.html

Here's a draft of the hiring announcement! (Accessible from inside the OCF subnet at https://fireball.ocf.berkeley.edu/announcements/2017-03-20/hiring if you want a live page)
Unfortunately I have a CS 170 midterm tonight, so I can't be at BoD and discuss this, but leave suggestions for what to change on this pull request (and push changes) and hopefully we can merge it tonight so that we can publicize it a lot more this week.
Obligatory screenshot:
One thing I'm not sure about is the sidebar to the right, it seems like it's a little unnecessary, but it also felt really empty without having it there. My intention with it was to give some background on the OCF and our impact (and a picture, since otherwise it's a wall of text), but something else might work better there. I also like …

Add hiring announcement

---

ocfweb/docs/docs/services/account.md

This isn't really to reassure alumni (most don't express concern for their privacy when they email in docs) but to make sure staff delete private data when it's no longer needed.

Dutifully destroy documents delivered by alumni

---

ocfweb/stats/job_frequency.py
ocfweb/stats/semester_job.py
ocfweb/stats/templates/stats/printing.html
ocfweb/stats/urls.py

Adding semester-wise weekday/weekend job distribution graphs. You can also adjust adjust the start and end date of the url request to adjust to time interval that is being queried. 
Suggestions on graph locations/titles/labels and Code Reviews?
(also it is possible to use the code from semester_job.py to create daily job graph by making some changes not sure if you guys want it or not)
http://supernova:8977/stats/printing/

Semester job

---

ocfweb/api/hours.py

The hours that are currently being used by opstaff is linked below.
https://docs.google.com/spreadsheets/d/1FHgW0wCnAh49bZIw54eoBT9xEoJ3AGG7Y2LhQdi0Lvs/edit#gid=0
we might need to consider changing the table entries to opstaff usernames depending our needs

changed hours spreadsheet

---

ocfweb/account/templates/account/vhost_mail/index.html

When I was setting up mail-hosting for some of my student groups, I would have to sift through the documentation or google it.  This way once vhosting is setup for a group the link is right there to instructions.

link to vhost instructions

---

ocfweb/docs/docs/services/web/django.md

fix trailing whitespace

---

ocfweb/about/templates/about/staff.html

about 9 people came last monday at 7:00pm asking when BoD was. these are new staffers we'd ideally like to direct to our new staff meetings, so we should change this wording asap

change default meeting to staff meeting

---

ocfweb/docs/docs/contact.md
ocfweb/docs/docs/services/lab/printing.md
ocfweb/docs/templates/docs/lab.html
ocfweb/main/templates/main/staff-hours.html

mostly just used "front desk staff" when possible b/c people won't know what OCF Operations Staff are, and am worried that people will confuse that more with OCF (volunteer) staff.

remove old references to pmc

---

requirements-dev.txt
requirements-minimal.txt
requirements.txt

hopefully, at least. 
django-bootstrap-form 3.3 has been released, as noted earlier, with fixes for Django 1.11.

django 1.11: third time's the charm

---

ocfweb/api/hours.py

We were dropping a lot of shifts before resulting in perforated hours on the site.
After much pdb-ing, issue was found to be wrong variable name used.

fix hour display bug

---

ocfweb/docs/docs/staff/tips.md
ocfweb/docs/docs/staff/tips/desktoprc.md

Technically, this particular page could go in the regular documentation instead of the staff docs, but "OCF power users" and "OCF staff" are virtually synonymous, and I can see the "tips and tricks" section getting expanded with staff-specific stuff in the future.

Add .desktoprc examples for staff

---

ocfweb/docs/docs/staff/procedures/setting-up-mdraid.md

The LSI RAID stuff has already been done for our servers and new servers we get should be in JBOD mode already, so the MegaRAID and WebCLI stuff can typically be skipped since it's usually set up correctly already.

Separate mdraid docs into sections

---

ocfweb/docs/docs/services/mirrors.md
ocfweb/templates/base.html

We don't really publicize our software mirrors anywhere, so I thought it would be good to put a list of projects we mirror somewhere on the website.

Add software mirrors to services

---

Jenkinsfile

I found [JENKINS-31086](https://issues.jenkins-ci.org/browse/JENKINS-31086) which seems to be exactly the problem we're having. It links to https://github.com/jenkinsci/pipeline-plugin/pull/266 which provides an option to fix it, so hopefully the build eventually passes!
EDIT: [Here's an example where this occurs](https://jenkins.ocf.berkeley.edu/blue/organizations/jenkins/ocfweb/detail/PR-318/7/pipeline). Thanks to @jvperrin for [finding out what was causing the failure](https://gist.github.com/jvperrin/5ca1f0976d1617f728a6631d7511d4d0).

Fix missing files on Jenkinsfile unstash

---

ocfweb/account/vhost.py
ocfweb/account/vhost_mail.py

Flake8 was complaining during testing, so I added the specific [exception](https://docs.python.org/3/library/socket.html#socket.herror).
It also complained about a bare except in vhost_mail.py, but I looked in PyMySQL's source code and the connection object throws several exception types, so a bare except is probably OK there.

Specify the exception type gethostbyaddr() throws.

---

ocfweb/templates/base.html

This seemed to have general support when I mentioned it on IRC yesterday (technically I proposed changing our desktop home pages, but this also works).
This shows the modal in the screenshot below on all ocfweb pages, only on the first page view. I added a custom title (wanted to include "OCF" in the text, to maybe make it seem less spammy) and turned off GA tracking on the modal. Also the "countdown" theme seemed to be the least confusing, so I went with that one.
Thoughts?

Proposal: add temporary net neutrality modal on ocfweb pages

---

Dockerfile
Dockerfile.static.in

Should resolve #218 
Unfortunately, yui-compressor's output wildcard syntax fails when there's only one input file through the wildcard, so I had to hardcode minifying the CSS file.

Auto-minify JS and CSS.

---

ocfweb/stats/summary.py

the ocflib.lab.printing is deprecated.  I believe this is the last caller in our repos of it at least when I search our github

move off of ocflib.lab.printing

---

ocfweb/docs/docs/staff/scripts/approve.md

This just documents that OID should be 0 when approving non student group accounts.

Add clarification to approve docs for non-student groups

---

ocfweb/account/templates/account/vhost/index.html
ocfweb/account/vhost.py

The request reason field was originally added to the form back when anyone could fill it out. Its intended purpose was to discourage frivolous requests. Today, the vhost form is only accessible by those who are eligible for vhosting, and this field serves no useful purpose.

Remove request reason field from vhost form

---

ocfweb/context_processors.py
ocfweb/errors/errors.py
ocfweb/settings.py
ocfweb/templates/404.html
ocfweb/urls.py

There were some complications with loading static pages when DEBUG was set to False to test the 404 page on supernova. I was able to get around this and load the static files by adding `--insecure` when running `manage.py runserver`.

Fixed previous error404 commit

---

ocfweb/docs/docs/staff/procedures/backporting-packages.md

Add build tools description to docs, update some references from jessie to stretch (`¯\___(ツ)___/¯`), describe a bit about what `dquilt` is and how it works since I had no idea it was an alias until I searched a bunch online, emphasize using docker containers for clean builds, and make it possible to copy/paste the `scp` command at the end (I've wanted to be able to do that for a while now).

Update packaging docs a bit

---

Jenkinsfile

This is like ocf/dns#20, ocf/ocflib#131, and ocf/puppet#347 in that it switches the Jenkinsfile to be declarative. It also starts using our [shared pipeline library](https://github.com/ocf/shared-pipeline), which is especially nice for this repo because it removes the shared marathon deploy stuff and puts it into version control!

Declarative jenkinsfile

---

.coveragerc
Jenkinsfile
Makefile
pytest.ini
requirements-dev-minimal.txt
requirements-dev.txt
requirements.txt

Once #388 is merged to change the structure of the `Jenkinsfile`, we should also start running `make coveralls` instead of `make test` so that coverage starts getting reported again (it was last reported in 2016).
This is the ocfweb equivalent of ocf/ocflib#134.

Use pytest-cov for coverage reporting, bump requirements

---

ocfweb/tv/templates/tv/labmap.html

Destruction was fixed today so it should be available on labmap again

Removing destruction from auto-occupied on ocf.io/tv/labmap

---

ocfweb/about/templates/about/lab-open-source.html
ocfweb/about/templates/about/lab-vote.html
ocfweb/about/templates/about/staff.html
ocfweb/account/templates/account/register/index.html
ocfweb/account/templates/account/vhost_mail/index.html
ocfweb/announcements/announcements.py
ocfweb/announcements/templates/announcements/2016-02-09-printing.html
ocfweb/announcements/templates/announcements/2016-04-01-renaming.html
ocfweb/announcements/templates/announcements/2016-05-12-ocf-eff-alliance.html
ocfweb/announcements/templates/announcements/2017-03-01-hpc-survey.html
ocfweb/announcements/templates/announcements/2017-03-20-hiring.html
ocfweb/announcements/templates/announcements/index.html
ocfweb/docs/templates/docs/partials/host.html
ocfweb/lab_reservations/templates/lab_reservations/index.html
ocfweb/stats/job_frequency.py
ocfweb/stats/semester_job.py
ocfweb/stats/session_count.py
ocfweb/stats/session_length.py
ocfweb/templates/404.html
ocfweb/templates/base.html
ocfweb/templates/partials/head.html
ocfweb/templates/partials/open-source-pics.html
ocfweb/tv/templates/tv/labmap.html

These can be seen in the test output, like in https://jenkins.ocf.berkeley.edu/job/ocfweb/job/master/1390/consoleFull (for example)
Aside from the existing tests, I've manually checked the affected pages (stats, announcements, some pages with template changes) to make sure they load properly on my dev instance.

Fix some django/matplotlib deprecation warnings

---

ocfweb/about/templates/about/lab-survey.html

scrolling, like the other iframe attributes, is deprecated
but still supported by all major browsers.

Remove survey iframe scrollbar

---

ocfweb/docs/docs/services/vhost/mail.md

An explanation of our historical mail hosting offering isn't really necessary IMO. I've rewritten this section to hopefully give a better explanation of what we do. I also added a screenshot of the admin panel so people understand exactly what they have control over.
I also modified references to the phrase "mail hosting" since this isn't a service we provide. "Mail virtual hosting" is still a strange term, but we use it in enough places that I think it's fine to keep it.
Closes #407.

Clarify mail docs

---

ocfweb/docs/views/officers.py

This makes the officers page flow more nicely.
cue bikeshedding on why we shouldn't do this

Reverse list of officers so recent terms are on top

---

ocfweb/component/markdown.py
ocfweb/docs/docs/staff/backend/libvirt.md
ocfweb/docs/docs/staff/backend/switch.md
ocfweb/docs/docs/staff/tips/shorturls.md
tests/component/markdown_test.py

I think the added test and docstring explain what this does pretty well, as well as the [GFM docs](https://github.github.com/gfm/#backslash-escapes) on this. Basically, I added this because a lot of editors people have (mine included) strip trailing whitespace, but it's actually used in markdown for hard line breaks (`<br>` tags), which is unfortunate. Now, with this change, adding a backslash before the newline at the end of a line will add in a line break (just like adding two spaces before the newline did before), but backslashes in the middle of a line will just function as normal.
Thoughts?
I also removed some of the duplication with the HTML comment mixins, since they can just share a class as far as I can tell for both inline and block lexers.
As a side note, backslash escaping …

Allow markdown hard line breaks without trailing spaces

---

ocfweb/api/hours.py
ocfweb/api/urls.py
ocfweb/context_processors.py
ocfweb/docs/templates/docs/lab.html
ocfweb/docs/views/lab.py
ocfweb/main/home.py
ocfweb/main/templates/main/home.html
ocfweb/stats/daily_graph.py
ocfweb/templates/base.html
ocfweb/templatetags/lab_hours.py

Next part of the great migration. This migrates ocfweb to use the new hours API.
I've mostly tested this, but there could be some tricky edge cases that I missed.

Use new hours2 library

---

services/web/nginx/nginx.conf

Resolves #463. This should pass in upstream headers from Apache.

web: pass upstream HTTP headers to django

---

ocfweb/about/templates/about/staff.html

Usually when people ask for ways to get involved, I point them to the mailing list and get involved pages. These should be on our "official" recruitment page. I've updated it to fit in with what we usually tell new staffers.

Add links to the staff recruitment page

---

ocfweb/docs/docs/staff/getinvolved.md

These should have been here the whole time but I recently learned that we could do these searches. Way easier then telling people to check all the repos manually.

staffdocs: add GitHub issues links to getinvolved page

---

ocfweb/docs/docs/staff/backend/kubernetes.md

staffdocs: replace haproxy with nginx for kubernetes

---

ocfweb/docs/docs/contact.md

Based on the Spring 2019 MLK Town Hall slides, and from UPS vendor feedback. We were using outdated mailing address.

Correct OCF physical address

---

ocfweb/docs/docs/staff/procedures/ssh-supernova.md

The idea here is to have more comprehensive pages in our repos about how to contribute and test changes. All of those will link to this page, which should be a basic guide about how to get into `supernova`.
This is a very early draft, so any kind of feedback is appreciated.

staffdocs: add page for SSHing into supernova

---

conf/ocfweb.conf

The newer redis requires using a new URL schema.

Fix redis connection

---

ocfweb/docs/docs/staff/procedures/printing.md

Now we don't need to go to the printers to find out what their IDs are, we can just use this page for reference.

staffdocs: add listing of printer IDs

---

ocfweb/docs/docs/staff/getinvolved.md

This search will sometimes show parts of our code that just happen to say "todo". Enabling case on this search will eliminate some of these, since actual todo's will always be in all caps.

staffdocs: add case:yes to sourcegraph-todo link in getinvolved

---

ocfweb/docs/docs/services/web/django.md

Add back the django webhosting docs (previously a mostly blank page that just said to use apphosting) that were removed in 3c51a6d3e460fd7423e93f7f022778ed777eb24a

Update django web hosting docs

---

ocfweb/component/lab_status.py

In the future we should probably move the banner's HTML and CSS to within ocfweb and have the yaml file specify the text.

Change get_lab_status() to read from ocf's etc repo.

---

ocfweb/api/staff_hours.py
ocfweb/api/urls.py

Exposes our staff hours to the API. Uses the existing cached function.

Add Staff Hours to API

---

ocfweb/docs/docs/staff/procedures/granting-privileges.md

the parens and quotes here aren't necessary, this makes it easier to type

staffdocs: make command for adding new staff less verbose

---

ocfweb/docs/views/servers.py

ocf.io/servers currently has overheat and tornado listed twice.

don't add tornado and overheat twice to server listing

---

ocfweb/stats/printing.py

Due to the power outage, no data was collected on 2019/10/10, so ocf.io/stats/printing would throw a KeyError when trying to display the missing data.
I added this to fill in the blanks for the last month's worth of data in case another power outage / server issue happens again.
```python
for day in (date.today() - timedelta(n) for n in range(30)):
if day not in pages_printed.keys():
pages_printed[day] = defaultdict(int)
```
Now all the tests pass again :D

Fix 500 Error on stats/printing

---

ocfweb/docs/templates/docs/servers.html

We now have more than four servers, and some are kubernetes workers/HPC nodes. This commit updates the text to reflect that.
Resolves #545.

docs: update servers page text

---

LICENSE
README.md
ocfweb/announcements/templates/announcements/2016-02-09-printing.html
ocfweb/component/markdown.py
ocfweb/docs/docs/about.md
ocfweb/docs/docs/about/formerstaff.md
ocfweb/docs/docs/contact/irc.md
ocfweb/docs/docs/services/hpc.md
ocfweb/docs/docs/services/shell.md
ocfweb/docs/docs/services/vhost.md
ocfweb/docs/docs/services/web/flask.md
ocfweb/docs/docs/services/web/php.md
ocfweb/docs/docs/services/web/wordpress.md
ocfweb/docs/docs/staff/backend/firewall.md
ocfweb/docs/docs/staff/backend/kerberos.md
ocfweb/docs/docs/staff/backend/mail.md
ocfweb/docs/docs/staff/procedures/accounts/association.md
ocfweb/docs/docs/staff/procedures/backporting-packages.md
ocfweb/docs/docs/staff/procedures/dmca.md
ocfweb/docs/docs/staff/procedures/editing-docs.md
ocfweb/docs/docs/staff/procedures/printing.md
ocfweb/docs/docs/staff/procedures/vhost.md
ocfweb/docs/docs/staff/rebuild/rt.md
ocfweb/docs/templates/docs/lab.html
ocfweb/templates/partials/open-source-pics.html

This branch is pretty much just me looking at all the `http:` links and seeing if they can be turned into `https:` links.
When I found a dead link I tried to replace it with a working link; if I couldn't find one (particularly on the "where did alumni go" page), I removed the link rather than have a broken link or a link pointing to a domain parking page. (My thinking is that these domains are probably no longer owned by the original organization and could point anywhere in the future.)
There are about 10 remaining actual HTTP links that I wasn't able to update (not counting things like XML schema references, vendored code, intentional uses of an HTTP link, etc.).

Convert as many HTTP links to HTTPS as possible

---

ocfweb/docs/templates/docs/officers.html
ocfweb/docs/views/officers.py

This updates the officers page to include recent elections. It also adds committee heads to the officers page. I didn't add committee heads to the "previous officers" section, because I wasn't sure how to do it (and we don't have any official historical committee heads). We should think about if we want to do this and if so how.
Ideally this can be merged when the new terms take effect on December 21.

update officers page and add committee heads

---

README.md
ocfweb/docs/docs/contact/slack.md
ocfweb/docs/docs/staff/startertasks.md
ocfweb/docs/docs/staff/startertasks/completed.md

These changes expand the starter tasks and also update info on the Slack page. Recommended to review commit by commit.

Expand starter tasks

---

ocfweb/docs/docs/staff/scripts/signat.md

https://github.com/ocf/ocflib/pull/199 leftovers

Update Callink API to use new URL

---

ocfweb/docs/docs/staff/powers.md

We don't use InCommon any more since we're now using entirely Let's Encrypt (I guess we missed this in both #572 and #550?)

Remove InCommon access from staff privileges doc

---

ocfweb/docs/docs/staff/procedures/vhost.md

Since ocf/etc#108 these configs are in the ocf/etc and we're switching that to be the source of truth. I also updated some of the language here around how quickly updates for new vhosts/apphosts/mailhosts go through the pipeline and tested viewing the page through a local copy of ocfweb to make sure it looks reasonable and the new links load.

Update vhost config instructions ot use ocf/etc

---

ocfweb/docs/templatetags/docs.py

This moves from this (which I found a bit confusing until I realized it was done by path so `vhost.md` and `xmpp.md` are near the end even though their titles would not lead to that same position):
To something like this:
(taken from the table of contents on https://www.ocf.berkeley.edu/docs/staff/)

Sort docs by title instead of path

---

ocfweb/docs/docs/staff/backend/libvirt.md
ocfweb/docs/docs/staff/procedures/live-resize.md

Finally! Over 3 years as a gist is probably enough time :P
This should replace the usage of https://gist.github.com/jvperrin/776a45dc68bf9fd91b3dae47b4aee32a and I'll try and edit that guide to point to the official docs once this is merged.
I did make a decent number of changes in content (displaying more sample command output, adding an assumptions section, some organization, etc.), so I'd appreciate any read throughs of it all!

Finally move my live disk resizing guide to the docs

---

ocfweb/account/templates/account/vhost/index.html
ocfweb/account/vhost.py

Previously we were trying to compare with a stringified boolean,
resulting in the condition being true all the time. This should be
clearer and also avoid the mess with using a BooleanField (since
browsers may not submit a BooleanField that is false.

Fix incorrect detection of requested vhost domain type

---

ocfweb/docs/docs/communications/blm.md
ocfweb/main/templates/main/home.html
ocfweb/static/scss/pages/_home.scss
ocfweb/templates/base.html

In addition to the homepage wording changes shown in the screenshot, I also made it say "$1000 total" instead of just "$1000".

wording fixes

---

ocfweb/account/commands.py

Not sure why this is but at some point `makemysql` broke with the following error:
`tee: /dev/tty: No such device or address`
I've not root caused this or figured out when it broke, but a workaround for now is to force paramiko to allocate a pseudo tty using get_pty. This actually also combines stdout and stderr but thats ok for now.

Allocate ptty

---

requirements.txt

It was not fun having 3.0.7 break `make dev` for literally everyone but it fixed a few critical vulnerabilities too.

Update Django to 3.0.8

---

ocfweb/docs/docs/communications/blm.md

As discussed in the summer meetings, I created a Google Form for BLM donations instead of having people individually email us. I made a simple change to blm.md so that the form is linked instead of the email. Also, a deadline was added for donations as well.

added Google Form link to BLM donation page

---

ocfweb/static/scss/pages/_stats.scss
ocfweb/static/scss/pages/stats/_summary.scss
ocfweb/static/scss/site.scss
ocfweb/stats/templates/stats/summary.html

When a table head is clicked (like "% Busy" or "Desktop"), the column will be sorted in ascending order. Click again to sort in descending order. Hold the "Control" key while clicking to reset the column order to default.
A demo is available at [trojan.ocf.berkeley.edu:8794/stats/](http://trojan.ocf.berkeley.edu:8794/stats/). Scroll down and click on the "% Busy" header to see the effect.

Sort the columns in the Today's Lab Utilization table when clicking on table heads

---

ocfweb/main/templates/main/staff-hours.html

This was causing the entire page after this tag to be bold.

staff-hours: Fix typo in closing <b> tag

---

kubernetes/ocfweb-static.yaml.erb

This is already present on [`ocfweb-web`](https://github.com/ocf/ocfweb/blob/f277cc3b77e15ae762b70b13c0fe6c3c33655836/kubernetes/ocfweb-web.yaml.erb#L78-L81) and [`ocfweb-worker`](https://github.com/ocf/ocfweb/blob/f277cc3b77e15ae762b70b13c0fe6c3c33655836/kubernetes/ocfweb-worker.yaml.erb#L47-L50) but isn't in `ocfweb-static` for some reason, so we're not getting any logs from it.

Add OCF search domain to ocfweb-static

---

ocfweb/templates/base.html

lab hours are not that useful when the lab is closed all semester. revert this when MLK opens.

Remove status bar

---

ocfweb/docs/views/buster_upgrade.py

HPC is on Buster now, and pileup/whirlwind are offline now (R.I.P.)

Update buster upgrade info

---

ocfweb/docs/docs/contact/irc.md

Unless this was some kind of snub against XMPP being simple, we probably
shouldn't say there are "three simple options" and then list four options.

docs/contact/irc: three options => four options

---

ocfweb/stats/templates/stats/session_stats.html

I didn't realize that the session stats was just hidden underneath a huge iframe.

Remove un-used Metabase iframe for session-stats

---

ocfweb/api/stats.py
ocfweb/api/urls.py
ocfweb/stats/mirrors.py

Currently building out ocfstatic stats page. These endpoints are for the summary page and use mostly old ocfweb stuff.
The reasoning behind this is that we can re-use the Django API from the old website (at least for now) and just serve the new static site.

Add endpoints for ocfstatic stats page

---

ocfweb/api/meeting_hours.py
ocfweb/api/urls.py

Adds endpoints to the newly-added meeting hours methods from ocflib. These methods will allows public access to an API that returns a list of weekly meetings, the next meeting, and the current meeting (if one is happening at the time). The corresponding ocflib pr can be reviewed [here.](https://github.com/ocf/ocflib/pull/238)

Add meeting hours endpoints

---

ocfweb/main/templates/main/staff-hours.html

Make ocf.io shortlink absolute and add mailto link for email.

Fix links on staff-hours page

---

ocfweb/account/templates/account/vhost/index.html
ocfweb/account/vhost.py
ocfweb/docs/docs/staff/procedures/vhost.md

The university hostmaster now requires answers to the following questions before approving a virtual host domain. I have updated all relevant documentation.
1. The purpose of the hostname, who will be using it and its relationship to the university's mission.
2. A responsible contact for the hostname.
3. Acknowledgment that all relevant university policies will be followed, including those pertaining to campus website accessibility. Those can be found here: https://dac.berkeley.edu/web-accessibility
(source: hostmaster ticket RITM0086801)

Add vhost hostmaster questions

---

ocfweb/account/vhost.py

I did a small oops and initialized the `href` in the wrong place, so it looks like the below. This PR moves the initialization of the label to the correct location. See #767.

Fix hostmaster link on vhost form

---

ocfweb/docs/docs/staff/getinvolved.md

One initiative we are working towards is to make contributing at the OCF more accessible and to provide organized activities for new staff to participate in for the first few weeks of the semester.
While we figure out a more permanent home for the starter tasks and projects currently being developed by internalcomm and decalcomm, here is a new section in the "getting involved" page that we can direct new staff to when they ask how they can start contributing.
More info about staff training can be found at https://github.com/0xcf/decal-web/pull/400.
Any additional resources or suggestions of starter tasks to add are welcome!

Add starter tasks section to docs
