- ocfweb/static/scss/site.scss
> Fix penguin logo css

- Makefile
- ocfweb/main/home.py
- ocfweb/main/templates/home.html
- ocfweb/static/scss/pages/home.scss
> home: make lab hours look reasonable

- ocfweb/component/markdown.py
- ocfweb/static/scss/pages/docs.scss
> Fix overreaching CSS breaking links inside headings

- ocfweb/docs/docs/services/vhost.md
- ocfweb/docs/docs/services/vhost/badges.md
- ocfweb/urls.py
> Migrate web badges page

- ocfweb/component/markdown.py
- ocfweb/docs/docs/services/web/flask.md
- requirements.txt
- setup.py
The styles/colors are not too great, but we can make them better later.
Before:
After:
> markdown: add simple code highlighting

- ocfweb/context_processors.py
- ocfweb/main/home.py
- ocfweb/main/templates/home.html
- ocfweb/static/scss/pages/home.scss
- requirements.txt
- setup.py
This fixes #7 
We should move the Google Maps map to the wiki page (which should no longer be a wiki page anyway), but imo not blocking the site launch. I actually like this better since the map was slow to load and jumped on page refresh.
It doesn't look too great so suggestions welcome, but I think we can do that in a followup so that we can start launching the site.
> Add links to home page

- ocfweb/main/templates/home.html
- ocfweb/static/scss/site.scss
- ocfweb/templates/base.html
* Reduce navbar spacing on sm so that the navbar items fit:
* Adjust hours columns on sidebar
* Wrap "Hours:" along with the actual hours
* Wrap "Sound like you?" with "Join the staff team!"
> Minor responsive fixes to size sm

- ocfweb/docs/templates/doc.html
- ocfweb/docs/templates/partials/doc-toc.html
- ocfweb/docs/templatetags/docs.py
- ocfweb/static/scss/pages/docs.scss
This seriously needs styling, and code review, so please take a look.
> Make docs ToC responsive, collapsible

- ocfweb/main/move_to_mlk.py
- ocfweb/main/templates/move-to-mlk.html
- ocfweb/static/scss/pages/move-to-mlk.scss
- ocfweb/static/scss/site.scss
- ocfweb/templates/partials/new-google-map.html
- ocfweb/templatetags/google_maps.py
- ocfweb/urls.py
- requirements.txt
https://www.ocf.berkeley.edu/mlk
> Moving page

- ocfweb/main/templates/move-to-mlk.html
@jvperrin @matthew-mcallister @kpengboy
> Make the walking GIF autoplay

- ocfweb/settings.py
- ocfweb/stats/summary.py
- ocfweb/stats/templates/summary.html
- ocfweb/urls.py
- requirements.txt
- setup.py
This moves some more stats to ocfweb. It doesn't look very great but neither did the old page, and we can improve it later.
It's also pretty slow...
> Add start of new stats page

- ocfweb/docs/urls.py
- ocfweb/urls.py
- requirements.txt
- setup.py
Updates the Django version and fixes a new warning.
Automated tests pass and I did some testing of random pages which seem to still work.
> Django 1.9

- ocfweb/docs/templates/lab.html
- ocfweb/templates/base.html
- ocfweb/templatetags/lab_hours.py
Compare original:
With reformatted:
> Less awkward lab hours format

- ocfweb/caching.py
- tests/caching_test.py
- tests/conftest.py
caching is hard to test in dev, let's add some tests
> Refactor caching, add tests

- ocfweb/component/forms.py
- ocfweb/login/ocf.py
- ocfweb/login/templates/ocf/login.html
- ocfweb/settings.py
- requirements.txt
- setup.py
> Make the login form look better

- ocfweb/docs/docs/services/shell.md
- ocfweb/docs/docs/staff/procedures/new-desktop.md
- ocfweb/docs/docs/staff/procedures/vhost.md
Addresses https://github.com/ocf/ocfweb/issues/97, plus an unrelated commit. Not sure why I held onto this so long.
> Mention user disk quotas

- ocfweb/account/register.py
- ocfweb/account/templates/chpass/index.html
- ocfweb/account/templates/partials/password-requirements-sidebar.html
- ocfweb/account/templates/partials/policies.html
- ocfweb/account/templates/register/already-has-account.html
- ocfweb/account/templates/register/cant-find-in-ldap.html
- ocfweb/account/templates/register/index.html
- ocfweb/account/templates/register/pending.html
- ocfweb/account/templates/register/success.html
- ocfweb/account/templates/register/wait/error-no-task-id.html
- ocfweb/account/templates/register/wait/error-probably-not-created.html
- ocfweb/account/templates/register/wait/wait.html
- ocfweb/static/scss/pages/account.scss
- ocfweb/static/scss/pages/account/register.scss
- ocfweb/static/scss/site.scss
> Improve registration form appearance

- ocfweb/about/templates/staff.html
- ocfweb/static/scss/pages/about/about-staff.scss
> Update hello for spring 2016 meetings

- ocfweb/stats/summary.py
- ocfweb/stats/templates/summary.html
> Silence printer errors (don't email staff)

- setup.py
> Workaround broken build by downgrading libsass

- ocfweb/settings.py
Fixes #130. Well, in theory anyway, it has to be tested first.
> Retry renaming csrf token

- ocfweb/stats/daily_graph.py
- ocfweb/templatetags/lab_hours.py
This might get in the way of jvperrin's highcharts branch, but it makes sense to do this anyways as we can be more flexible with our hours now if we wish.
> Use datetime.time for lab hours

- ocfweb/docs/docs/services/web.md
- ocfweb/docs/docs/services/web/php.md
- ocfweb/docs/docs/services/web/rails.md
don't want to merge this quite yet
> Update docs for jessie death

- ocfweb/stats/printing.py
- ocfweb/stats/templates/partials/stats-navbar.html
- ocfweb/stats/templates/printing.html
- ocfweb/stats/templates/summary.html
- ocfweb/stats/templatetags/stats.py
- ocfweb/urls.py
- setup.py
A first start at better printing stats in ocfweb
> Add simple semester printing histogram

- ocfweb/stats/accounts.py
- ocfweb/stats/templates/accounts.html
- ocfweb/stats/templatetags/stats.py
- ocfweb/urls.py
> Add some simple account graphs

- ocfweb/docs/docs/staff/procedures/vhost.md
Markdown newline and trailing whitespace rule seems to not work well..
> Document app hosting

- ocfweb/account/commands.py
- ocfweb/account/templates/commands/index.html
> Make commands look better

- debian/rules
> Fix broken build by pinning pip==8.0.3 for dh-virtualenv

- ocfweb/docs/doc.py
- ocfweb/docs/templates/docs/doc.html
- ocfweb/static/scss/pages/docs.scss
> Add page history button on markdown docs

- ocfweb/account/register.py
- ocfweb/account/templates/account/register/already-has-account.html
> Improve the "You already have an account!" page

- ocfweb/docs/docs/docs/constitution.md
Proposed amendment by me. Voting will take place via email under section 8.1.1.2.
> constitution: amend amendment and dissolution processes

- ocfweb/docs/docs/services/web/wordpress.md
See https://github.com/ocf/ocfweb/issues/169
> update wordpress import/export docs

- ocfweb/account/templates/account/vhost_mail/index.html
- ocfweb/context_processors.py
- ocfweb/docs/docs/services/vhost.md
- ocfweb/docs/docs/services/vhost/mail.md
- ocfweb/docs/docs/services/vhost/mail/gmail.md
- ocfweb/login/ocf.py
- ocfweb/templates/base.html
Comments welcome. Leaving this PR open until we're ready to launch, then I'll merge it right before we do the transition.
One note: we don't have a way to include images in Markdown that are hosted in the app itself currently, so the images are on fluffy.cc. We should fix that eventually but I don't think it's a blocker.
> Add vhost mail docs and link (rt#5219)

- ocfweb/wsgi.py
This should hopefully prevent the long timings taken on the first request of each worker (especially noticable on Mesos since we don't have tons of monitoring hitting it) where it's basically just importing our code.
> Attempt to warm up workers in wsgi module

- Jenkinsfile
> Clean Jenkins workspace when switching nodes

- ocfweb/docs/docs/services/mail.md
It already pretty much said this, but this is a little more explicit.
> Clarify both student groups + individuals need contact emails

- ocfweb/docs/docs/staff/backend/backups.md
Making a PR for demo purposes.
> docs/backups: We have 6TB drives in hal now

- ocfweb/stats/accounts.py
- requirements.txt
See https://github.com/ocf/ocflib/pull/38.
> Fix compatibility with ldap3 version 2

- Dockerfile
- Makefile
> Pass ocflib version as argument to docker build

- ocfweb/docs/docs/staff/procedures/new-host.md
I'll leave this PR open in case our puppet structure changes soon.
> Update new host creation docs

- ocfweb/docs/docs/staff/backend/rt.md
- ocfweb/docs/urls.py
> First Creation of RT Documentation

- ocfweb/stats/printing.py
- ocfweb/stats/templates/stats/printing.html
Our data is bad on the new printers, so the charts aren't too great for them. deforestation is missing data since I only imported data for current printers into MySQL, I'll fix that soon.
> Add table of toner changes

- ocfweb/stats/printing.py
- ocfweb/stats/templates/stats/printing.html
- ocfweb/templatetags/common.py
looks kinda bad, but it's a giant chart, so idk
someone can improve later maybe
i spot-checked that the numbers match stats.ocf.b.e
> Add pages printed per day

- ocfweb/about/templates/about/staff.html
- ocfweb/docs/urls.py
- ocfweb/static/scss/site.scss
- ocfweb/templates/base.html
Added some links so that it's easier for people to learn more about the software listed if they want to.
> Add links at bottom of page and pics on /about/staff

- ocfweb/docs/docs/staff/procedures/installing-updates.md
see https://github.com/ocf/ocfweb/pull/226#issuecomment-268108033
> Add reference to suspend/wakeup per jvperrin

- ocfweb/docs/docs/staff/procedures/vhost.md
> docs: Correct required DNS records for vhosting

- ocfweb/docs/docs/staff/scripts/how.md
- ocfweb/docs/docs/staff/scripts/note.md
- ocfweb/docs/docs/staff/scripts/sorry.md
- ocfweb/docs/docs/staff/scripts/unsorry.md
per @kpengboy and #232 
please help me add more details
> initial commit of sorry docs

- ocfweb/stats/summary.py
- ocfweb/stats/templates/stats/summary.html
If I haven't made some serious error I think these three PRs take care of the issue @jvperrin mentioned.
> add staff_in_lab_count

- ocfweb/static/scss/pages/_docs.scss
- ocfweb/static/scss/pages/docs/_servers.scss
ignore the first and last commits in this branch
> use variables in site.scss in other places

- Jenkinsfile
lol let's see how many tries it takes to get this right
> Make "make test" and "make cook-image" run in parallel

- ocfweb/docs/docs/contact.md
- ocfweb/docs/docs/faq.md
- ocfweb/docs/docs/services/account/content-removal.md
just a draft, we should have a policy outlined for when people email us like about the Campanile.
> begin documenting content removal policy

- ocfweb/templates/base.html
> add faq link to footer

- ocfweb/docs/docs/staff/procedures/vhost.md
> signatories must make requests

- Makefile
> add lint option to makefile

- ocfweb/docs/templates/docs/officers.html
- ocfweb/docs/views/officers.py
What do you think of the layout? Any other suggestions on how to display DGMs and DSMs?
> docs: add DGM and DSMs

- ocfweb/docs/docs/staff/backend/printhost.md
Minor things may change, but this ought to cover most of it.
http://supernova.ocf.berkeley.edu:8108/docs/staff/backend/printhost/
> Document the printhost

- ocfweb/account/templates/account/vhost/index.html
- ocfweb/account/templates/account/vhost/not_eligible.html
- ocfweb/account/vhost.py
- ocfweb/docs/docs/services/vhost.md
- tests/account/vhost_test.py
Not the best code ever, but apparently there are already people lined up for this, and I think it would be helpful in the long run to make the form available for everyone rather than to have them email us and negotiate on a case-by-case basis.
> Allow faculty to request virtual hosts

- ocfweb/docs/docs/services/vhost.md
[rt#5167](https://ocf.io/rt/5167)
> add blurb about relevant subdomain

- ocfweb/account/register.py
- ocfweb/login/calnet.py
- ocfweb/stats/accounts.py
continue updating to remove ocflib.constants
obviously this build will not work until ocflib is updated
> Move constants

- ocfweb/docs/docs/services/web/wordpress.md
> docs: add instructions for WP .htaccess when moving URL

- .pre-commit-config.yaml
- ocfweb/account/vhost.py
pyupgrade is a pretty cool pre-commit hook for "upgrading" old python syntax to newer, more canonical syntax. You can see a list of the transformations it can currently apply: https://github.com/asottile/pyupgrade#implemented-features
> Add pyupgrade

- requirements-dev.txt
- requirements-minimal.txt
- requirements.txt
> trying again: update to django 1.11

- ocfweb/docs/docs/staff/procedures/accounts/alumni-reset.md
- ocfweb/docs/docs/staff/scripts/unsorry.md
steps to take when alumni need access to their disabled accounts. Anything I got wrong or topics I may have missed?
> alumni account reset documentation

- ocfweb/docs/docs/services/web/django.md
Removed all the docs about actually making a new Django app, they were outdated and not exhaustive and probably most people already have an app by the time they're looking for hosting. Replaced that with a link to the official Django docs.
I tested this with my own account. It did work eventually, but initially I made a typo in `run.fcgi` which caused the first version of my app to fail, and then I was never able to get it to work until after I restarted apache on death :\
Something else to look into...
(Note that if you're going to attempt these steps yourself, you'll want to do it from tsunami and not supernova, since supernova is running stretch whereas the webserver is still jessie.)
> Update Django docs to work with new Django

- ocfweb/account/vhost_mail.py
- tests/account/vhost_mail_test.py
> Trim spaces in more places

- ocfweb/docs/docs/about/formerstaff.md
edits by alanw, cardi, dmchan, elliot, geo, gordeon, jchu, sherryg
> Add previous and current companies of OCF alumni

- ocfweb/stats/mirrors.py
- ocfweb/stats/templates/stats/mirrors.html
- ocfweb/stats/templatetags/stats.py
- ocfweb/stats/urls.py
- requirements-minimal.txt
[rt#6177](https://ocf.io/rt/6177)
Maybe some pretty line graphs in the future
> add mirrors stats to stats page

- ocfweb/api/hours.py
- ocfweb/api/urls.py
the ocfweb counterpart to ocf/ocflib#75
> api: move hours to ocfweb

- ocfweb/docs/docs/staff/policies.md
- ocfweb/docs/docs/staff/policies/keycard.md
Can it be officially promulgated?
> Add keycard policy

- ocfweb/docs/docs/staff/policies/staff-policy.md
- ocfweb/docs/docs/staff/procedures/restarting-services.md
> add staff policy

- ocfweb/api/hours.py
I don't think this is a good long-term solution but it should work for now. Once the other parts of big brother are in place wrt tracking if opstaff actually came to their shifts I think this should be rewritten.
> hours: fix for display

- ocfweb/docs/docs/staff/backend/backups.md
Some of the language might be a bit clunky, but I have tested all of the restoration steps. I tried to make them general enough that they could be followed but didn't want to make a script for restoring when it would just get out of date and (hopefully) never need to be used, so I figured docs were a better way to go.
> Add backup restoration docs and remove completed backup improvements

- ocfweb/account/chpass.py
- ocfweb/account/templates/account/partials/chpass-no-accounts.html
- ocfweb/docs/docs/services/account.md
> account.chpass: Show error when no accounts found

- ocfweb/docs/views/lab.py
- ocfweb/stats/daily_graph.py
cut out calls to REGULAR_HOURS, I think this should work for now to stop the ocfweb deploy problems
> tentatively fix ocfweb->ocflib->ocfweb dependency problem

- ocfweb/component/celery.py
Same as https://github.com/ocf/create/pull/12, https://github.com/ocf/approve/pull/4, and https://github.com/ocf/ircbot/commit/ca9483b04d4b7.
> Enable SSL verification for celery

- ocfweb/docs/docs/staff/scripts/approve.md
> change approve docs title so it's obvious this is for group accounts

- ocfweb/stats/daily_graph.py
Added a dashed line representing total desktops in the daily graph
> Horizontal line of total desktops for stats/daily-graph

- ocfweb/docs/templates/docs/lab.html
A few people e-mail help asking if we have scanners.  Hopefully this will clear that up a bit
> mention scanners

- ocfweb/docs/docs/staff/policies/lab-reservation-policy.md
Transcription of lab reservation policy for OCF staff written by Alex Welty
@sahilhasan
> Create lab-reservation-policy.md (staff version)

- ocfweb/docs/docs/services/vhost.md
Related to https://github.com/ocf/templates/pull/7
> header for ocf banner

- ocfweb/docs/templates/docs/account_policies.html
- ocfweb/docs/templates/docs/partials/account-policies.html
github is smart and suggested kpengboy as a requestor
> add non-warranty clause

- ocfweb/docs/docs/docs/operatingrules/constitution.md
see https://www.ocf.berkeley.edu/~staff/bod/2017/Fall/2017-11-20
> change quorum to 1/2 from 2/3

- ocfweb/stats/printing.py
- ocfweb/stats/templates/stats/printing.html
Made changes on #339 to show toner numbers on website
> Toner calculation on webpage

- .gitignore
- ocfweb/account/recommender.py
- ocfweb/account/register.py
- ocfweb/account/templates/account/register/index.html
- ocfweb/account/urls.py
- ocfweb/static/js/pages/account/quick_username_validation.js
- ocfweb/static/js/pages/account/recommend_username.js
- tests/end_to_end_test.py
Also added recommender.py in ocflib
> Added username recommendations and quicker verification

- ocfweb/account/templates/account/register/index.html
- ocfweb/static/js/pages/account/quick_username_validation.js
- Fix JS Path
- Clean up username feedback code
> Fix JS path

- ocfweb/account/templates/account/register/index.html
- ocfweb/static/js/pages/account/quick_username_validation.js
- ocfweb/static/js/pages/account/recommend_username.js
- ocfweb/static/scss/pages/account/_register.scss
- Move styling to _register.scss
- Change variable names to be more consistent
> Move styling to _register.scss

- ocfweb/docs/docs/staff/procedures/granting-privileges.md
IST > ASUC > IST > EECS > IST > ASUC > SAIT
> only took 6 months to figure out who can get new people onto the firewall

- ocfweb/login/templates/login/ocf/login.html
- ocfweb/login/urls.py
- ocfweb/static/scss/pages/_login.scss
- ocfweb/static/scss/site.scss
> Add password reset link to login page

- ocfweb/stats/accounts.py
- ocfweb/stats/templates/stats/accounts.html
- ocfweb/stats/urls.py
Changed stats/accounts graphs from matplotlib to highcharts
> changed accounts graphs to highcharts

- ocfweb/docs/docs/services/hpc.md
Hopefully we can merge this quickly, some of the trial users are confused about usage and I believe this will help them substantially.
> HPC Documentation

- conf/ocfweb.conf
- ocfweb/account/vhost.py
- ocfweb/api/labstats.py
- ocfweb/api/session_tracking.py
- ocfweb/api/urls.py
- ocfweb/context_processors.py
- ocfweb/settings.py
- tests/api/session_tracking_test.py
- tests/end_to_end_test.py
same as the puppet PR, this has been working for the last few days but I'm going to let it continue testing for a few more
feedback is appreciated
> session tracking -> ocfweb

- ocfweb/docs/docs/staff/procedures/printing.md
- ocfweb/stats/printing.py
We no longer buy our own toner or maintain our own printers. Our time of suffering is over, and those stronger than us have taken over our burden. May they be blessed with the strength necessary to maintain that which we chose not to.
> update printing docs

- ocfweb/main/openbugbounty.py
- ocfweb/main/security.py
- ocfweb/urls.py
We need to add a file like this to reregister for [OpenBugBounty](https://www.openbugbounty.org)
> Add security.txt for OpenBugBounty

- ocfweb/docs/docs/staff/backend/firewall.md
- ocfweb/docs/docs/staff/backend/internal-firewalls.md
Does it make sense to you all? Suggestions for improvement?
> Add internal firewall docs

- ocfweb/docs/docs/contact/slack.md
This is in preperation for the first general meeting of Fall 2018.
Resolves #392
> Add Slack Documentation

- ocfweb/about/lab.py
- ocfweb/about/templates/about/lab-vote.html
- ocfweb/static/scss/pages/about/_lab-open-source.scss
- ocfweb/urls.py
A page urging people vote. This could probably look prettier, so suggestions are welcome. Once this is done, I intend to make this the desktop homepage.
It looks like this:
> Add vote page

- ocfweb/docs/docs/staff/procedures/dmca.md
I made us an account at the Lumen database, so this PR adds better instructions for how to use it.
> Add Lumen database instructions

- requirements.txt
From warning about CVE-2018-18074 from Github.
> Update requests to 2.20.0

- .pre-commit-config.yaml
- ocfweb/account/chpass.py
- ocfweb/account/register.py
- ocfweb/api/lab.py
- ocfweb/docs/docs/staff/backend/backups.md
- ocfweb/docs/docs/staff/backend/kerberos.md
- ocfweb/login/calnet.py
The title pretty much explains it, this upgrades the existing hooks, and then adds a few more hooks from the standard hooks repo (and fixes some things caught by the hooks).
> Upgrade pre-commit hooks, add a few additional hooks

- ocfweb/docs/docs/staff/procedures/vhost.md
accompanying https://github.com/ocf/puppet/pull/423
> rename ocfdev to ocfapphost

- ocfweb/docs/docs/staff/backend/switch.md
- ocfweb/docs/docs/staff/procedures/setting-up-lacp.md
some provisional docs on configuring LACP
> add some docs for configuring LACP

- ocfweb/stats/mirrors.py
- ocfweb/stats/summary.py
- ocfweb/stats/templates/stats/mirrors.html
> show total bandwidth used in mirrors stats

- ocfweb/settings.py
- ocfweb/urls.py
- requirements.txt
This could help us with investigating the create celery errors, among other things. I assume this is fine, but gonna put this PR here in case there's anything I should be aware of.
> Add prometheus metrics measuring

- ocfweb/docs/docs/membership/banning.md
Updates the banning policy to reflect the language voted on and passed at the BoD meeting on Dec 3, 2018.
> Update the Banning Policy

- ocfweb/docs/docs/membership/banning.md
> Banning Policy Updates

- ocfweb/docs/docs/staff/getinvolved.md
Thanks to everyone who helped prepare the first draft for this! This PR serves as a final round of feedback on this document. This page will be read by a lot of newbies (we expect a big influx this Monday, and I'll mention it in the meeting) so I'd like a lot of eyes on it.
> staffdocs: Add getinvolved page

- .pre-commit-config.yaml
This is now supported by flake8! If this gets merged I'll move all the other repos as well.
> Use new flake8 pre-commit

- ocfweb/docs/docs/services/web.md
- ocfweb/docs/docs/services/web/php.md
- Update the versions of software shown on the main web hosting page for death on stretch
- Update the php modules shown and add links
> Update webhost docs

- ocfweb/docs/docs/services/web/jekyll.md
Update jekyll web hosting docs (tested, but feel free to test it again with any sites or setups you have)
> Update jekyll web hosting docs

- .pre-commit-config.yaml
- ocfweb/docs/docs/services/web/rails.md
Update rails web hosting doc (tested, but feel free to test it again with any sites or setups you have), and I needed to edit the pre-commit config because otherwise the shebang was detected as a top level header.
> Update rails web hosting docs

- ocfweb/docs/docs/contact/irc.md
Many hours died to bring you these ZNC docs.
> Update IRC docs with ZNC setup instructions

- ocfweb/account/commands.py
> Add decode to output and error

- ocfweb/docs/docs/docs/operatingrules/constitution.md
These changes clarify procedures surrounding special elections.
> make constitutional amendments proposed in rt#7790

- ocfweb/docs/docs/membership/eligibility.md
> eligibility: add wording clarifying GA critera

- ocfweb/docs/docs/services/account.md
re rt#7565
perhaps someone has better ideas for wording than I do
> add short data retention statement

- ocfweb/api/shorturls.py
- ocfweb/api/urls.py
requires https://github.com/ocf/ocflib/pull/154
> add functionality for bouncing shorturls

- .pre-commit-config.yaml
- Dockerfile
- Makefile
This *should* hopefully be all that is required.
> Switch ocfweb to Python 3.7

- .pre-commit-config.yaml
- Dockerfile
- Makefile
> Revert "Switch ocfweb to Python 3.7"

- ocfweb/docs/docs/staff/backend/kubernetes.md
Hope I am not learning another piece of English. Otherwise just close this pr thanks :3
> fix (I think) typo on kubernetes staff docs

- README.md
The README currently lists the wrong makefile command to update requirements.
> fix README update-requirements

- ocfweb/docs/docs/services/lab/lab-reservation-policy.md
- ocfweb/docs/templates/docs/lab.html
> Change lab info page to include our new standing desk.

- .pre-commit-config.yaml
- Dockerfile
- Makefile
- ocfweb/account/chpass.py
- ocfweb/account/vhost.py
- ocfweb/account/vhost_mail.py
- ocfweb/announcements/announcements.py
- ocfweb/api/session_tracking.py
- ocfweb/bin/run_periodic_functions.py
- ocfweb/caching.py
- ocfweb/component/markdown.py
- ocfweb/docs/markdown_based.py
- ocfweb/docs/urls.py
- ocfweb/docs/views/officers.py
- ocfweb/docs/views/servers.py
- ocfweb/lab_reservations/reserve.py
- ocfweb/settings.py
- ocfweb/stats/daily_graph.py
- ocfweb/stats/job_frequency.py
- ocfweb/stats/summary.py
- ocfweb/templatetags/google_maps.py
- ocfweb/templatetags/lab_hours.py
- tests/account/vhost_mail_test.py
- tests/api/session_tracking_test.py
Bless @asottile for pyupgrade.
> Update to Python 3.7 \o/

- ocfweb/settings.py
It needs to wait for puppet to run on all of the marathon agents.
> [DO NOT MERGE] Remove replacement

- ocfweb/login/ocf.py
This also serves as a test of the new approval-required-before-merge feature
Fixes: #501
> login: don't allow sorried accounts to log in

- ocfweb/docs/docs/staff/procedures/hpc.md
shitty, shitty docs
Closes: #464
> docs: add staff instructions for HPC

- README.md
I tried to make the README clearer to complete beginners to OCF infra, but more suggestions are welcome.
> Update language in README

- ocfweb/docs/views/officers.py
> im the gm now

- ocfweb/docs/docs/contact/irc.md
- ocfweb/docs/docs/services/xmpp.md
- ocfweb/docs/docs/staff/procedures/xmpp.md
This adds a few pages for XMPP to our docs. It's currently very minimal, if anyone has suggestions for details to add please feel free to suggest.
> docs: add XMPP

- ocfweb/api/announce.py
- ocfweb/api/urls.py
Pretty much the same deal as #520. This could probably be improved by adding a limit parameter on the get request to get the few most recent blog posts, might do that later.
> Add Blog to API

- ocfweb/docs/docs/staff/backend/libvirt.md
virsh stop isn't a real command
> staffdocs: change `virsh stop` to `virsh shutdown`

- kubernetes/ocfweb-web.yaml.erb
- kubernetes/ocfweb-worker.yaml.erb
- ocfweb/environment.py
> fix version detection in kubernetes

- ocfweb/docs/docs/staff/startertasks.md
This page can be useful for new staffers who want to do stuff but don't feel ready to make contributions.
Thanks to everyone who gave feedback on the Google Doc draft. Any other feedback on this PR is appreciated, including suggestions for new tasks, writing style, etc.
I don't have access to OCF infra at the moment so I haven't tested this, but I'll test it before merging.
> staffdocs: add startertasks page

- ocfweb/docs/docs/services/lab/printing.md
100 -> 200 per semester
10 -> 20 per weekday
> Updated Printing Quota to match current 9/30/19

- ocfweb/stats/printing.py
* Updated `105` to `SEMESTERLY_QUOTA + 5`
Fixes #552.
> [#552] fix histogram on printing page

- ocfweb/docs/docs/staff/procedures/accounts/renaming.md
Document how to 'rename' a username based on rebuild [discussion](https://moffle.fuqu.jp/ocf/%23rebuild/20191017#L5)
> Document how to change a username

- tests/account/vhost_test.py
Apparently there are records at asdfghjkl.berkeley.edu now...
> fix NXDOMAIN test

- ocfweb/docs/docs/services/shell.md
> update SSH host keys for tsunami

- ocfweb/docs/docs/staff/procedures/granting-privileges.md
> Delete section on giving people Comodo SSL

- ocfweb/docs/docs/staff/procedures/ssl.md
The [current SSL docs page](https://www.ocf.berkeley.edu/docs/staff/procedures/ssl/) mentions a bunch of stuff about InCommon/Comodo that's no longer relevant now that we use Let's Encrypt everywhere with dehydrated + DDNS + puppet.
> Update SSL docs with Let's Encrypt details

- ocfweb/account/constants.py
> add cooperc to TESTER_CALNET_UIDS

- ocfweb/docs/docs/staff/backend/munin.md
- ocfweb/docs/docs/staff/backend/prometheus.md
I created some Grafana dashboards today and noticed that there was no documentation on Prometheus or Grafana in the OCF docs. So here it is :)
Feel free to contribute to to it; I'm sure there are plenty of things in the configs that I missed/have no idea exist and should be documented.
> Add documentation for prometheus

- ocfweb/docs/docs/staff/procedures/new-host.md
Also, add a link to the IP allocation spreadsheet.
See ocf/utils#142.
> update info on ldap-add-host

- ocfweb/docs/docs/staff/startertasks/completed.md
- ocfweb/docs/docs/staff/tips/twitch.md
Thanks to @cg505 for writing this up
> Add tips on Twitch/OBS streaming from @cg505 to staffdocs

- ocfweb/main/templates/main/home.html
- ocfweb/stats/templates/stats/printing/pages-printed.html
spleling eror ohn teh hmoepgea :(
> generic spellcheck pr

- ocfweb/docs/docs/staff/powers.md
- ocfweb/templates/base.html
- ocfweb/templates/partials/google-analytics.html
> Remove Google Analytics

- ocfweb/account/constants.py
- ocfweb/account/register.py
- ocfweb/account/templates/account/register/index.html
- ocfweb/docs/docs/membership.md
- ocfweb/static/js/pages/account/register.js
Sure there's only a few weeks left in the online semester but this would be useful over breaks and during unexpected extended lab closures.
I've mostly tested this by hand up except the part about creating the actual group account since that would need actual credentials, but will make sure to test before/if we merge.
> Allow groups to sign up via web interface

- ocfweb/docs/docs/staff/startertasks/completed.md
> add ~njha to pr completion

- ocfweb/api/stats.py
- ocfweb/api/urls.py
Some small additions to the API.
> Added num users and staff to api

- ocfweb/docs/templates/docs/officers.html
- ocfweb/docs/views/officers.py
Also, update the Officers page to support historical committee heads.
> add Fall 2020 officers

- ocfweb/docs/views/officers.py
This PR builds off #602. Please comment if I have done something unadvisable or unidiomatic (I am not that experienced in Python typing).
> Use dataclasses and stricter typing in officers module

- ocfweb/templates/base.html
> Add donation button

- ocfweb/docs/views/buster_upgrade.py
> maelstrom and flood upgraded to buster

- ocfweb/main/templates/main/home.html
- ocfweb/templates/partials/google-map-static.html
- ocfweb/templatetags/google_maps.py
> change map to static

- ocfweb/docs/views/buster_upgrade.py
optimistic that this puppet run will succeed
EDIT: it didn't but it works now
> add reaper to upgraded list

- ocfweb/about/templates/about/staff.html
- ocfweb/docs/docs/staff/getinvolved.md
- ocfweb/docs/docs/staff/procedures/restarting-services.md
- ocfweb/docs/docs/staff/startertasks.md
> Update docs to link to Matrix and Discord

- ocfweb/account/templates/account/register/index.html
- ocfweb/docs/docs/membership.md
https://github.com/ocf/ocflib/issues/136
> Remove similarity heuristic

- ocfweb/docs/docs/privacy.md
- ocfweb/templates/base.html
We went through this wording for a couple of weeks now. There's also a link on the home page.
> Add privacy policy

- ocfweb/docs/docs/docs/operatingrules/bylaws.md
Amendment doc: https://docs.google.com/document/d/1mVEbmZOxiiP8fLYxyOUYIgcrs8D0Y9lN2GorOYojy2g/edit
Approved by BoD on 2020-09-09.
> Finance bylaw amendments

- ocfweb/docs/docs/docs/operatingrules/constitution.md
Amendment doc: https://docs.google.com/document/d/16jZGeIX9I5MdJ-lfJZAKUiLrm-1HJcSmayl-LYm0mBY/edit
Approved by BoD on 2020-09-09.
> Ranked choice constitution amendment

- ocfweb/main/templates/main/home.html
- ocfweb/templates/base.html
Literally a near revert from what the https://github.com/ocf/ocfweb/pull/609/commits/e1f17e836ba4968d49c0d02749da6b663f4f312c did
> Remove the BLM Banners

- ocfweb/docs/docs/staff/procedures/installing-updates.md
> update apt-dater link

- ocfweb/static/scss/pages/_home.scss
- ocfweb/static/scss/site.scss
closes #637
Maybe some people want to keep it how it is right now? If so, feel free to close this PR and the issue.
> revert remaining BLM changes

- .pre-commit-config.yaml
- ocfweb/account/vhost.py
- ocfweb/bin/run_periodic_functions.py
- ocfweb/middleware/errors.py
- tests/component/markdown_test.py
This should now allow pre-commit to pass even if there isn't a venv.
> Exclude .activate.sh from pre-commit

- ocfweb/docs/views/officers.py
https://vote.heliosvoting.org/helios/elections/e19cb5a2-351b-11eb-99ae-a69ca61afb81/view
https://vote.heliosvoting.org/helios/elections/9ed3e7a6-2e02-11eb-8e47-728b230603ff/view
> Add sp2021 officers

- ocfweb/templates/base.html
I should be studying for a final right now
> replace ruby with kubernetes

- .pre-commit-config.yaml
This broke my PR https://github.com/ocf/ocfweb/pull/667
> Clone the submodule for pre-commit ci

- ocfweb/docs/docs/communications/stf-renewal.md
- ocfweb/templates/base.html
> Add STF renewal page & banner

- ocfweb/docs/docs/docs/operatingrules/bylaws.md
Discussed and voted for in BoD (4/13/21)
Proposed changes doc: https://notes.ocf.berkeley.edu/_xCCkPtWRD29ax_bA4gkvQ?both
> Add service committee in bylaws

- ocfweb/docs/docs/communications/stf-renewal.md
- ocfweb/templates/base.html
Reverts ocf/ocfweb#683
I totally forgot STF was in danger of not passing :(
> Revert "switching banner to announce STF passing"

- ocfweb/docs/docs/membership/eligibility.md
Updated instructions for letter to email in eligibility requirements where things like departmental letterhead were not needed.
> make updates to eligibility

- ocfweb/docs/views/officers.py
spring semester just finished :)
> add fall 2021 officers

- ocfweb/docs/docs/communications/stf-renewal.md
- ocfweb/templates/base.html
I should test this before it is merged.
> Remove STF banner and note that it did not pass :((

- ocfweb/docs/docs/staff/getinvolved.md
Updating our meeting times. Don't want to confuse any new members!
> Update meeting times

- ocfweb/about/templates/about/staff.html
> staff meeting is wednesday

- ocfweb/about/templates/about/staff.html
> actually update meeting time

- ocfweb/main/templates/main/staff-hours.html
Small, inconsequential error but was annoying
> Fix a small 404 on the staff hours page

- ocfweb/docs/docs/docs/operatingrules/bylaws.md
- ocfweb/docs/docs/docs/operatingrules/constitution.md
> Revert "Update Constitution"

- ocfweb/docs/docs/staff/procedures/printing.md
Fix docs according to https://github.com/ocf/utils/issues/101.
> Add docs for CLI printer removal

- ocfweb/static/js/pages/account/register.js
> Display account association warning on page load if applicable

- ocfweb/docs/docs/about/formerstaff.md
Hi there, Dots is the startup @sahilhasan and I work at.
> Update former staff

- Dockerfile
> Bump Dockerfile base image

- ocfweb/account/commands.py
> Fix disk quota command arguments

- ocfweb/docs/docs/staff/startertasks/completed.md
OCF staff training task 9/27/2023
> add jimfang to PR starter task

- ocfweb/account/templates/account/vhost/index.html
- ocfweb/account/vhost.py
> feat: update wording for non studentorg berkeley address and added static/application hosting type options
